version: '2'

services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    ports:
        - 6379:6379
    volumes:
        - ./config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
